application: crowyapp
#version: 20121204a
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

#- url: /admin/.*
#  script: controller/admin.py
#  login: admin

- url: .*
  script: controller.main.application
  secure: optional

#メンテナンス中
#- url: .*
#  static_files: static/maintenance.html
#  upload: static/maintenance.html

builtins:
- remote_api: on


libraries:
- name: django
  version: 1.2
env_variables:
  DJANGO_SETTINGS_MODULE: 'conf.settings'